### ISSUE TITLE
Error executing `/Script Examples/Python/testing_example.py`

### ISSUE THREAD

**Issue by fivesails** [openhab-scripters/openhab-helper-libraries#177]
**When executed, a**  
`ValueError: when: "Item TestNumber1 received update" could not be parsed because Item "TestNumber1" is not in the ItemRegistry`
occurs.
**To Reproduce**
1. copy `/Script Examples/Python/testing_example.py` to the appropriate folder

**Environment (please complete the following information):**
 - Jython version: 2.7.0 standalone
 - openHAB version: 2.4.0, Release

**Additional context**
1. I think,this error occurs because the `@when` decorator is expanded before the unit test creates the items.
If the creation of the Trigger is delayed, the unit test runs fine on my system. I attach that version: 
[testing_2_example.py.txt](https://github.com/openhab-scripters/openhab-helper-libraries/files/3349258/testing_2_example.py.txt)
2. In the current version of the library, the methods in `core.items` are `add_item()` iso `add()` and `remove_item()` iso `remove()`.
3. The items are not required therefore removed from the files' first comment

**Comment by openhab-5iver** [comment]
Thank you for pointing this out, @fivesails. There are many layers of issues with this example. I've never gotten around to really going through this module, but I'd like to start using it to build out tests that use each of the modules. There have been several bugs introduced in the script as the core modules evolved. Definitely, the functions in core.items are `add_item` and `remove_item`. The when decorator does validation of the Items, but I'm not sure yet [how it worked](https://github.com/openhab-scripters/openhab-helper-libraries/blob/original_(%3C%3D2.3)/scripts/examples/testing_example.py) before with [the old decorator](https://github.com/openhab-scripters/openhab-helper-libraries/blob/original_(%3C%3D2.3)/lib/openhab/triggers.py#L146).

Please submit a PR with your fixes so that others don't bump into this. At some point in the future, I'll dig into this module and example.

**Comment by fivesails** [comment]
Thank you for your reply, I submitted a [PR](https://github.com/openhab-scripters/openhab-helper-libraries/pull/179)
