### ISSUE TITLE
[Feature Request] Create an installation/update script

### ISSUE THREAD

**Issue by openhab-5iver** [openhab-scripters/openhab-helper-libraries#48]
An installation script would make it easier for first-time users to setup JSR223-Jython, as well as update existing installations. It should:

* Recognize OH installation directories, or prompt for location
* Prompt for whether the Jython standalone jar should be included
* Prompt for where to create/update EXTRA_JAVA_OPTS
* Pull latest from this repo, extract, and copy core package and scripts to correct locations, overwriting if they already exist
* Create directories for community and personal, if they do not exist
* Create __init__.py files for community and personal, if they do not exist
* Possibly, provide menu for installing community submissions

I already have a script built up for [manual installation of the zwave and zigbee binding](https://github.com/openhab-5iver/openHAB-utils), which I plan to use as a starting point.

**Comment by mjcumming** [comment]
Scott, I think this would be a great idea. What about building this as an option under openhabian?

**Comment by openhab-5iver** [comment]
I don't have experience with openHABian, but that's a good idea. I'll look into it, and take a look at how they do/prefer the scripting.

**Comment by mjcumming** [comment]
OpenHABian has been great for me. I have limited Linux knowledge and having a package like that to do the lifting made getting into OH possible for me.

**Comment by CrazyIvan359** [comment]
Recently I got a new box to use as my home server and I have switched to using Docker for just about every service, including openHAB. I wanted to be able to use this library and Jython without having to log in to the container and modify the startup settings every time, so I wrote an install script.

It's very basic right now, it just sets EXTRA_JAVA_OPTS as an environment variable when it runs. Then checks if the automation folder exists or is empty, if it is it clones the repo to a temp folder and brings the core over. It then downloads a Jython jar.

I would like to improve it so that it either searches for directories to install to, or that they can be passed in as env vars. 
I will move the Jython install location, Jython filename, and download URL to env vars. 

I have not been able to come up with a way to determine if files are different for updating purpose. These are some things I haven't figured out yet:
* Consider file deletions in the library, how would the script know that the file doesn't belong?
* Consider a situation where the user has modified one of the core files, the updater should recognize this and not overwrite the file without confirmation. 

I had thought about using git, but my entire OH conf *is* a git repo. This could be accomplished by using a submodule, but that would be beyond the scope of what an installer script should do. 

Thoughts and suggestions?

**Comment by openhab-5iver** [comment]
There are Jython and helper library addons pending approval and [a beta version available in the forum](https://community.openhab.org/t/beta-testers-wanted-jython-addon-w-helper-libraries-requires-oh-2-5-x/86633). An installation script is no longer necessary.
