### ISSUE TITLE
modules loaded by scripts do not generate an error message related to that module

### ISSUE THREAD

**Issue by mjcumming** [openhab-scripters/openhab-helper-libraries#59]
When loading a module from a jython script, if the module has an error, the logger shows the error coming from the script and not the module in question. The line number of the error is correct but no filename is given. This is problematic for modules which load other modules.

**Comment by openhab-5iver** [comment]
I have an update for the logging, which may fix this, and also adds a log attribute to the function as is done to a rule class. It's currently in the lucid migration branch, and I hope to have this merged by the end of the year, assuming there's someone to test it!

**Comment by mjcumming** [comment]
The files from the lucid branch look the same as in the main branch - last commit was 15 days ago.

**Comment by diijkstra** [comment]
I think this is a limitation of ESH, exception which is not handled by jython is logged with simple one liner. Are you sure, that line number is from offending module? For me, line is always set to line number of script (rule .py file) which is being run. 

To debug, you can try to add try/except block which logs exception with full stack:
````
try:
    import foo
except Exception as ex:
    log.error(traceback.format_exc()) # assuming log is logger
    raise ex # optional, makes ESH think that exception was thrown here
````
So this error:
````
18:54:39.189 [ERROR] [ript.internal.ScriptEngineManagerImpl] - Error during evaluation of script 'file:/openhab/conf/automation/jsr223/200_rules/foo.py': NameError: name 'foo' is not defined in <script> at line number 17
```
is now:
````
18:55:27.092 [ERROR] [ipse.smarthome.automation.rules] - Traceback (most recent call last):
  File "<script>", line 17, in <module>
  File "/openhab/conf/automation/lib/python/foo.py", line 1, in <module>
    bar
NameError: name 'bar' is not defined

18:55:27.094 [ERROR] [ript.internal.ScriptEngineManagerImpl] - Error during evaluation of script 'file:/openhab/conf/automation/jsr223/200_rules/foo.py': NameError: name 'foo' is not defined in <script> at line number 20
````
Same thing happens when code is executed.

**Comment by mjcumming** [comment]
Yes, the line number for the error comes from the script loading the module. Thank you for the work around, hope there is long term more elegant solution

**Comment by diijkstra** [comment]
I think you can safely put most stuff inside try block, imports, rules, initialization etc. Only thing you need to have outside is logger. @rule decorator adds these try/except to your rules by default.

I think that proper solution can be implemented only on ESH side. If I remember correctly, .py rule file is read and run via jython interpreter as script (not read by jython from file, hence <script> instead file path in jython stack trace. Since nothing is handling an error, ESH is just logging where it went bad.

**Comment by openhab-5iver** [comment]
There are a couple challenges to work out with migrating lucid, so I've added the changes I was referring to into master.

**Comment by openhab-5iver** [comment]
@diijkstra, do you planning to submit a PR to openhab-core?
